name: Build Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
        with:
          submodules: "recursive"
      - name: "Login with Github packages"
        uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ github.token }}"
      - name: "Setup buildx"
        uses: "docker/setup-buildx-action@v1"
      - name: "Build and push image"
        uses: "docker/build-push-action@v2"
        with:
          context: "./NeteaseCloudMusicApi"
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/ncmapi:${{ github.ref_name }}"
